# Generated by Django 3.2 on 2021-04-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50)),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50)),
                ('nickname', models.CharField(help_text='Введите никнейм', max_length=50)),
                ('password', models.CharField(help_text='Пароль', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(editable=False, upload_to='static/%Y/%m/%d/')),
                ('tags', models.CharField(help_text='Введите теги через пробел', max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author')),
            ],
        ),
    ]
